### ISSUE TITLE
라이센스 확정 부탁드립니다.

### ISSUE THREAD

**Issue by jungsooPark-dev** [synchrok/Eulrlega.cs#2]
유용한 기능을 개발해주셔서 감사드립니다. 최근에 업무에 이 기능을 사용하기 시작했습니다.
라이센스를 표준 오픈 소스 라이센스로 확정해주실 수 있을까요? 그러면 더 많은 분들이 개발해주신 기능을 이용할 수 있을 것 같습니다.

**Comment by synchrok** [comment]
MIT 라이센스 추가했습니다. 편하게 이용하셔도 좋습니다!
